#spring.application.name=cuisine-backend
#
#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USER}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#spring.web.resources.static-locations=file:uploads/
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.format_sql=true
#
#app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
#
#app.jwt-expiration-milliseconds=604800000
#
#server.port=8080
#
#logging.level.com.example.blog=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=5MB

spring.application.name=cuisine-backend

spring.datasource.url=jdbc:mysql://localhost:3306/cuisine
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.web.resources.static-locations=file:uploads/

# ?????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# JPA / Hibernate ??
# ========================================
# ????/?????
spring.jpa.hibernate.ddl-auto=update

# ??SQL??????????????????
spring.jpa.show-sql=true

# ???SQL??
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# JWT ???????
# ========================================
# JWT ?????????????????
# ???????????https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb

# JWT Token ????????
# 604800000 ?? = 7?
# 86400000 ?? = 1?
# 3600000 ?? = 1??
app.jwt-expiration-milliseconds=604800000

# ========================================
# ?????
# ========================================
server.port=8080

# ========================================
# ????????
# ========================================
# ??????
logging.level.com.example.blog=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB